version: '3'
services:
    feeds:
        image: receitas
        build: ./dockerfiles/servicos
        hostname: feeds
        ports:
            - '5000'
        volumes:
            - './feeds:/servico'
        command: python3 servico.py
        networks:
            receitasnet:
                ipv4_address: 172.29.1.1
    mysql:
        image: mysql
        restart: unless-stopped
        expose: 
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
        networks:
            receitasnet:
                ipv4_address: 172.29.1.2
    arquivos:
        image: arquivos
        build: ./dockerfiles/nginx
        volumes:
            - './assets/fotos:/usr/share/nginx/html'
        hostname: arquivos
        ports:
            - '80'
        networks:
            receitasnet:
                ipv4_address: 172.29.1.3
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        expose:
            - '8084'
        environment:
            PMA_HOST: mysql
        networks:
            receitasnet:
                ipv4_address: 172.29.1.4

networks:
    receitasnet:
        ipam:
            driver: default
            config:
                - subnet: 172.29.1.0/16
